--- # my conditional playbook
- hosts: all
  user: ansible
  connection: ssh
  become: true

  tasks:
    - name: install apache for debian
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"


    - name: install apache for redhat
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"
