--- # copy a file from server to host
- name: my test playbook
  hosts: all
  user: ansible
  become: true
  connection: ssh


  tasks:
    - name: copying a file from server to host
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: rohit
