--- # create a directory
- name: my test playbook
  hosts: all
  user: ansible
  become: true
  connection: ssh

  tasks:
    - name: creating a directory
      file:
        path: /home/ansible/kailashdir
        state: directory
