--- # create user account
- name: my test playbook
  hosts: all
  user: ansible
  become: true
  connection: ssh

  tasks:
    - name: creating a user
      user: name=rohit
      ignore_errors: yes

