---
- name: multiple s/w install
  hosts: all
  become: true

  tasks:
    - name: install packages
      yum:
        name: ['git','which','docker','mysql','tree','wget','httpd','java']
        state: present
