---
- hosts: all
  user: ansible
  connection: ssh
  become: true



  tasks:
    - name: creating file with ansible playbooks
      file: path=/tmp/hari.txt state=touch

    - name: creating a folder with playbook
      file: path=/tmp/raj123 state=directory


    - name: copying a file to hosts
      copy: src=./file100 dest=/home/ansible
