--- # install multiple packages/loop
- hosts: all
  become: true

  tasks:
    - name: install s/w's
      yum: name = ''{{item}}'' state = installed
      with_items:
        - httpd
        - tree
        - docker
        - java
