--- # exicute two tasks
- name: my test playbook
  hosts: all
  become: true
  user: ansible
  connection: ssh

  tasks:
    - name: installing pkges
      yum:
        name: httpd
        state: present

    - name: start service
      service:
        name: httpd
        state: started     
