---
- hosts: all
  become: yes

  tasks:
    - name: creating multiple users
      user: name='{{item}}' state=present
      with_items:
        - abhi
        - priya
        - rakesh
        - rajesh
        - anu
        - romi
