--- # new variable creation
- hosts: all
  become: true
  user: ansible
  connection: ssh


  vars:
    user: sunny 


  tasks:
    - name: create a  user '{{user}}'
      user:
        name: "{{ user}}"
